# Generated by Django 5.0.3 on 2025-07-17 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0002_matricula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudante',
            name='cpf',
            field=models.IntegerField(max_length=11),
        ),
    ]
