# Generated by Django 5.0.3 on 2025-07-18 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0003_alter_estudante_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudante',
            name='cpf',
            field=models.IntegerField(max_length=11, unique=True),
        ),
    ]
